# Generated by Django 3.2.4 on 2021-06-08 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('excerpt', models.TextField(null=True)),
                ('poster', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 6, 8, 6, 53, 36, 20776))),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=120)),
            ],
        ),
    ]
