# Generated by Django 3.2.4 on 2021-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210621_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Contenu',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='Sous_titre',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Image2',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Image3',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
