# Generated by Django 3.2.4 on 2021-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210625_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='Image1',
        ),
        migrations.AlterField(
            model_name='post',
            name='Image2',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image3',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
