# Generated by Django 3.2.4 on 2021-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210625_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='path',
        ),
        migrations.AddField(
            model_name='upload',
            name='Image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
