# Generated by Django 3.2.4 on 2021-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210625_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
