# Generated by Django 3.2.4 on 2021-06-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image1',
            field=models.ImageField(max_length=255, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/'),
        ),
    ]
