# Generated by Django 3.2.4 on 2021-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210625_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='./static'),
        ),
    ]
