# Generated by Django 3.2.4 on 2021-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image1',
            field=models.ImageField(max_length=255, null=True, upload_to='blog/static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='blog/static/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='blog/static/'),
        ),
    ]
