# Generated by Django 3.2.4 on 2021-06-29 17:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210625_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Contenu',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
