# Generated by Django 3.2.4 on 2021-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='textEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Contenu',
            field=models.TextField(null=True),
        ),
    ]
